### ISSUE TITLE
-v is not working

### ISSUE THREAD

**Issue by kaushik041** [thekoushik/tempit#1]
`tempit -v` shows
```
ReferenceError: VERSION is not defined
```

**Comment by thekoushik** [comment]
Oops!
I'll look into it ASAP!

**Comment by thekoushik** [comment]
fixed in [6aeb3ffcad7eaba9f9b9eed6e6121a65af553de3](https://github.com/thekoushik/tempit/commit/6aeb3ffcad7eaba9f9b9eed6e6121a65af553de3)
